version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
